POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "userName": "test",
    "email": "test@gmail.com",
    "password": "test123",
    "gender": "Male",
    "DOB": "1999-01-01",
    "createdAt": "2021-01-01"
}

###

# POST http://localhost:5000/api/user/login
POST https://eji4acf735.execute-api.ap-south-1.amazonaws.com/prod/api/user/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "userName": "test",
    "password": "test123"
}

###

GET http://localhost:5000/api/recipes?search_q=chicken&diet=vegetarian&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE3MTg5OTQ5Njh9.iGSZ43lG6vKk28ZiXJHOFwbj30YV_QxWDr9dOTLIJeI

###

GET http://localhost:5000/api/recipes/ingredients?ingredients=chicken,tomato,oil,pepper&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE3MTg5OTQ5Njh9.iGSZ43lG6vKk28ZiXJHOFwbj30YV_QxWDr9dOTLIJeI

###

GET http://localhost:5000/api/recipes/cuisine?cuisineType=Italian&search_q=chicken&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE3MTg5OTQ5Njh9.iGSZ43lG6vKk28ZiXJHOFwbj30YV_QxWDr9dOTLIJeI
